### ISSUE TITLE
Roc curve

### ISSUE THREAD

**Issue by ganav** [manuelaguadomtz/pyeer#1]
hello
thanks for nice source.
I have some suggestions as follows:
1. report.csv has roc columns with blanks between each row, which makes it difficult to be used.
for example 1
                    blanck
                    1
                    blank
                    1                 etc.
2. roc length is too big more than 600,000. So even opening csv takes time. 
   i cannot even copy or past or do anything in the csv file because roc is too large then 
  csv file get no response.
  in that case how about you resize the roc file by shrinking it into length of 100 or something.
thank you

**Comment by manuelaguadomtz** [comment]
Hi, first of all, thanks for using the PyEER package. I hope it is being useful to you. Having said that, here are my comments regarding your suggestion:

1. I have never experienced my self the blank rows between FMR or FNMR values. Nevertheless, I agree that this is an issue that needs to be fixed. I would deeply appreciate your help to accomplish that. Can you provide me with a simplified version of the CSV file at which you are referring?. In general, any details that you can share with me that allows me replicating this issue will be very helpful. I will also be helpful to know in which operating system and with which software are you opening the CSV file.

 2. I agree that when the length of the ROC curve is too big, manually handling the CSV file could turn into a nightmare. For a while back I was thinking about to save the ROC curve in a separated file so it becomes a lot easy to handle at least automatically from a script. Sincerely, it never crosses my mine to shrink the ROC curve since this could not be a desired effect for every user. However, I think that you have made a valid suggestion so I will think about which are the best strategies to follow in order to optionally shrink the ROC curve. Do you have any suggestion regarding the best strategies to shrink the ROC curve?

**Comment by ganav** [comment]
Yes can you please send me your email let me send you the CSV files and txt files.
I am using widows 10 and i open it with csv and excel.
pyeer is the last version i have installed.
There are several methods to shrink (resize, sample), simply you can have average like d=[1,2,3,4,5]=> d=[1.5, 2.5, 3.5, 4.5]) it is up to you.
but in my case my curve is too big, so for simplicity i have just skipped between numbers (d=[1,2,3,4,5]=> d=[1,3,5])

**Comment by manuelaguadomtz** [comment]
I deeply sorry about the delayed answer, I was at a scientific event. My email es manuelaguadomtz_at_gmail.com

best!

**Comment by manuelaguadomtz** [comment]
Since I have not heard any more from you from an extended period of time, I am closing this issue. Feel free to reopen it if you needed. best!
