### ISSUE TITLE
What is the correct format for the impostor scores?

### ISSUE THREAD

**Issue by tiwalade-odu** [manuelaguadomtz/pyeer#7]
Hi @manuelaguadomtz 
Thanks for providing the pyeer.

I got this error when I ran the pyeer for the histogram format:

```
UserWarning: It is possible that you had set the wrong score type. Please consider reviewing if you are using dissimilarity or similarity scores
  warn("It is possible that you had set the wrong score"
```
Also can you please explain what this line means in the readme file?

**File format: Each line contains the number of scores equals to the index of the line in the file (starting from zero).**

Thank you.

**Comment by manuelaguadomtz** [comment]
Hi @tiwalade-odu 

The message you are referring to is raised when the AUC is less than 0.5, or the last rank of the CMC is less than 0.2. Since these can be considered bad results, the system warns you may not have set the correct type of scores. By default, the system assumes that the provided scores are similarity scores, if you are working with dissimilarity scores you need to indicate it using the --ds parameter.

If you need to, you can check [here](https://jcsites.juniata.edu/faculty/rhodes/ml/simdissim.htm) the difference between similarity and dissimilarity measures. 

The histogram format is only supported for integer scores. If you are using integer scores, then you can create a histogram as follows

23   # number of scores = 0
12   # number of scores = 1
0    # number of scores = 2
1    # number of scores = 3
10  # number of scores = 4
...
...
...
234  # number of scores = n-1

I hope this example is more clear. 

Sorry for the delayed answer

**Comment by tiwalade-odu** [comment]
Thanks. I got it.
